name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.12.9
        uses: actions/setup-go@v1
        with:
          go-version: 1.12.9
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: GolangCI-Lint Action
        uses: actions-contrib/golangci-lint@v0.1.0
        args: run

#      - name: Run golangci-lint
#        run: golangci-lint run

      - name: Run go test
        run: go test

      - name: Run go build
        run: go build -v .
